version: '3'

services:
    frontend:
      build: ./client
      container_name: clientapp
      ports:
        - 3000:3000
      networks:
        - network-net
      depends on:
        - backend

    backend:
      build: ./backend
      container_name: backend
      ports:
        - 5000:5000
      networks:
        - network-net
      depends on:
        - mongo


    mongo:
      container_name: mongo_container
      image: mongo:latest
      restart: always
      volumes:
        - ./data:/data/db
      ports:
        - 27017:27017
      networks:
        - network-net

    networks:
      network-net:
      driver: bridge

  

      
        
