---
- name: Install required packages
 apt: 
   name: 
     -docker.io
     -nodejs
     -npm
   state: present
 -name  - name: Download and build Dockerimage for container for backend
  docker_image:
    name: victornzia/backendapp:v1.0
    state: present
    state: present