---
- name: Install git
  apt: 
    name: git
    state: present
 -name: Cloning the repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ dest_folder }}"
  version  ---
- name: Install required packages
 apt: 
   name: 
     -docker.io
     -nodejs
     -npm
   state: present
 -name  - name: Download and build Dockerimage for container for client
  docker_image:
    name: victornzia/clientapp:v1.0
    state: present
  version: master  
  register: git _checkout 
  tag: git