apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: yolo-app

spec:
  replicas: 3
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: victornzia/clientapp:v1.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongodb:27017/mongodb" 
